config/routes.rb
Groceries::Application.routes.draw do
  devise_for :users
  root to: "lists#index"

  resources :lists 
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :user
	has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
def index
	@items = Item.all
	end

	def create
    @item = Item.new(item_params)
	    if @item.save
	      redirect_to root_path
	  	else
	  	  render :new
	  	end
    end

    def new
	    @item = Item.new
	    #redirect_to root_path
    end

    def edit
	    @item = Item.find( params[:id])
	end

	def show
    	@item = Item.find params[:id]
    	 redirect_to root_path
  	end

	def update
	   @item = Item.find( params[:id])
	   safe_item_params = params.require(:item).permit(:name, :list_id)

	   if @item.update(safe_item_params)
	      redirect_to @item
	   else
	      render 'edit'
	   end
	end

    def destroy
	    item = Item.find(params[:id])
	    item.destroy
	    redirect_to root_path
	  end

private
	     def item_params
		    params.require(:item).permit(:name, :list_id)
		 end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def index
	@lists = List.all
	end

	def create
    @list = List.new(list_params)
	    if @list.save
	      redirect_to root_path
	  	else
	  	  render :new
	  	end
    end

    def new
	    @list = List.new
	    #redirect_to root_path
    end

    def edit
	    @list = List.find( params[:id])
	end

	def show
    	@list = List.find params[:id]
    	@item = Item.new
  	end

	def update
	   @list = List.find( params[:id])
	   safe_list_params = params.require(:list).permit(:name, :date_created)

	   if @list.update(safe_list_params)
	      redirect_to @list
	   else
	      render 'edit'
	   end
	end

    def destroy
	    list = List.find(params[:id])
	    list.destroy
	    redirect_to root_path
	  end

private
	     def list_params
		    params.require(:list).permit(:name, :date_created)
		 end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/edit.html.erb
<div class="main col-md-6 col-md-offset-3">
			<h1>Edit Item</h1>

		<%= form_for(@item) do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>
		<% end %>
	</div>

</div>

app/views/items/index.html.erb
index.html.erb

app/views/items/new.html.erb
<div class="main col-md-6 col-md-offset-3">
		<h1>Add Items to a Grocery List</h1>

	<%= form_for(@item) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>
	<% end %>

app/views/items/show.html.erb
show.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groceries</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "bootstrap" %>
</head>
<body>
	<div class="nav clearfix">
		<div class="header col-md-8 col-md-offset-1">
			<img src="http://hindiemedia.com/wp-content/uploads/2014/04/shopping_cart1.png" alt="shopping cart" class="shoppingCart">
			<h1 class="title"> Welcome to Grocery Buddy</h1>
		</div>
		<div class="signIn">
		<% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, style: 'color:#FFFFcc;' %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li> 
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </div>
	 	<p class="notice"><%= notice %></p>
	    <p class="alert" style="padding:0;"><%= alert %></p>
		</ul>
	</div>
    
<%= yield %>

</body>
</html>

app/views/lists/edit.html.erb
	<div class="main col-md-6 col-md-offset-3">
			<h1>Edit Grocery List</h1>

		<%= form_for(@list) do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.label :date_created %>
			<%= f.text_field :date_created %>
			<%= f.submit %>
		<% end %>
	</div>

</div>

app/views/lists/index.html.erb
<div class="row">

	<div class="main col-md-6 col-md-offset-3">
			<h2>Create a new List</h2>
		<button type="button" class="btn btn-default">>
			<%= link_to "New List", new_list_path %>
		</button>
		<h3> Here Are You Grocery Lists </h3>	
		<% @lists.each do |list| %>
		  <section>
		  	<h3><%= link_to list.name, list_path(list.id)%></h3>
		    <h4><%= list.date_created %></h4>
		    <h5>
			    <ul>
			    <% list.items.each do |item| %>
	   			<li><%= item.name%></li>
	 			<% end %>
	 			</ul>
 			</h5>
		  	<button type="button" class="btn btn-default"><%= link_to "Delete", list_path(list.id), method: 'delete' %></button>
		  	<button type="button" class="btn btn-default"><%= link_to "Edit Your List", edit_list_path(list) %></button>
		<% end %>
	</div>

</div>

app/views/lists/new.html.erb
	<div class="main col-md-6 col-md-offset-3">
		<h1>Create a New Grocery List</h1>

	<%= form_for(@list) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.label :date_created %>
		<%= f.text_field :date_created %>
		<%= f.submit %>
	<% end %>
	</div>

</div>

app/views/lists/show.html.erb
<div class="main col-md-6 col-md-offset-3">
	<h1><%= @list.name %></h1>

	<h4>Add new Item:</h4>

	<%= form_for @item do |f| %>
	   <%= f.label :name %>
	   <%= f.text_field :name %>
	   <%= f.hidden_field(:list_id, value: @list.id) %> 
	   <%= f.submit %>
	<% end %>
	<br/>
	<p><%= link_to "Back to home page", root_path %></p>
</div>